#!/bin/sh

echo "##############################################################"
echo "install script has been run..."
echo "##############################################################"

set -eu

# Homebrewのインストール
if ! command -v brew &> /dev/null; then
  echo "Homebrewが見つかりません。インストールを開始します。"

  # Homebrewをインストール
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo "Homebrewのインストールが完了しました。"

  # # パスを通すためにシェルの設定ファイルを更新
  # if [[ -n "$ZSH_VERSION" ]]; then
  #   echo 'eval "$(`which brew` shellenv)"' >> ~/.zprofile
  #   eval "$(`which brew` shellenv)"
  # elif [[ -n "$BASH_VERSION" ]]; then
  #   echo 'eval "$(`which brew` shellenv)"' >> ~/.bash_profile
  #   eval "$(`which brew` shellenv)"
  # fi

else
    echo "Homebrewは既にインストールされています。"
fi
if [ ! ]
# インストールしてもPATHが通ってないので、WARNINGメッセージに従ってPATHを通す。
which brew

if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone https://github.com/y-okamoto-1113/dotfiles.git
fi


# ブラウザのインストール
browsers=(
  google-chrome
  firefox
  tor-browser
)
for b in $browsers; do
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "now installing '${b}'..."
  brew install $b
done

dev_tools=(
  git
  git-secret
  docker
  docker-compose
  visual-studio-code
  anyenv
  asdf
  mysql
  nodenv
  nodebrew
  rbenv
  git-secrets
  fx
  golang
  google-cloud-sdk
  kubectl
  tfenv
  youtube-dl
  yt-dlp
  zsh-completions
  zsh-autosuggestions
  gitmoji-cli
  wget
  awscli
  figlet
)

# brew おすすめアプリ一覧
# https://blog.katsubemakito.net/macos/setup-macbookair2020
other_tools=(
  karabiner-elements
  tree
  monitorcontrol
  vlc
  5kplayer
  imageoptim
  imagemagick
  ffmpeg
  keka
  proxyman
  coteditor
  dbeaver-community
  lazydocker
  yarn
  gnupg
  chromedriver
)


hacker_tools=(
  sl
)


# Apple GitからHomebrew Gitに変更
# https://qiita.com/Nedward/items/2380fc49183331f0219a
# homebrewでgitをインストールした場合、インストール先が人によって違うっぽい？ので、パスを動的に生成するために無理やりエスケープ使いまくった。
# 本当は以下のコマンドを打ちたい。
# echo 'export PATH="/opt/homebrew/opt/git/bin/git:$PATH"' >> ~/.zshrc
homebrew_git_path=`brew --prefix git`
echo "export PATH=\""${homebrew_git_path}"/bin/git:\$PATH\"" >> ~/.zshrc

source ~/.zshrc


# dockerはcask
# Cask List
casks=(
  docker
  visual-studio-code
  notion
  dbeaver-community
  devtoys
  zoom
  slack
  clipy
  tableplus
  pushplaylabs-sidekick
  postman
)
for c in $cask; do
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "now installing '${c}'..."
  brew install --cask $c
done

# graphiqlはbrew経由でインストールすると、開けない。



anyenv install -l
anyenv install goenv
exec $SHELL -l
